name: Build_MP

on:  
  push:
    branches: [master]
  pull_request:
    branches: [ master ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
     
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
    
      - name: Build Linux
        run: dotnet publish ./MassBanTool_MP/MassBanToolMP.csproj -c Release -r linux-x64 --no-self-contained

      - name: Build Windows
        run: dotnet publish ./MassBanTool_MP/MassBanToolMP.csproj -c Release -r win-x64 --no-self-contained
                    
      # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
      - name: Upload Win artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MassBanTool_Win
          path: |
              D:\a\MassBanTool\MassBanTool\MassBanTool_MP\bin\Release\net6.0\win-x64\publish\*
              
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MassBanTool_Linux
          path: |
              D:\a\MassBanTool\MassBanTool\MassBanTool_MP\bin\Release\net6.0\linux-x64\publish\*
