name: Build_MP

on:  
  push:
    branches: [master]
  pull_request:
    branches: [ master ]

jobs:  
  build:    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
     
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
    
      - name: Build
        run: dotnet build ./MassBanTool_MP/MassBanToolMP.csproj -c Release
                    
      # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MassBanTool_MP
          path: |
              D:\a\MassBanTool\MassBanTool\MassBanTool_MP\bin\Release\net6.0\*
